### PR TITLE
Add Hindi Translation

### PR DESCRIPTION
**Pull request by anuragsingh6**
This pull request adds Hindi language support in [caesium](https://github.com/Lymphatus/caesium-image-compressor).

### CODE REVIEW

**Comment by Lymphatus** [comment]
Hi! Thanks for your contribution! I'm currently adding some new features involving a few new text lines to be translated. It would be great if you could update this PR once I add the new translations so the next release would be 100% complete. I'll let you know when the new files are available.
Many thanks!

**Comment by anuragsingh6** [comment]
Sure!

**Comment by Lymphatus** [comment]
Hi @anuragsingh6! All new strings are on the main branch if you want to take a look to them.
Thanks!

**Comment by anuragsingh6** [comment]
Hi @Lymphatus!
I have created a new PR from a new fork because I kind of messed up this one some where, so...
I hope that's okay?

Cheers!

**Pull request closed without merging**
