### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by nickyc975**
This PR adds Simplified Chinese translation for [caesium](https://github.com/Lymphatus/caesium-image-compressor).

### CODE REVIEW

**Comment by chachak** [comment]
Hi, here you are my Spanish translation (polished and finished).

[caesium_es_ES.zip](https://github.com/Lymphatus/caesium-image-compressor/files/10042343/caesium_es_ES.zip)

**Comment by chriszemp** [comment]
Hello really i like your work, for that i'm sharing with you my Greek translation
[caesium_el_GR.zip](https://github.com/Lymphatus/caesium-image-compressor/files/10087482/caesium_el_GR.zip)

**Comment by Lymphatus** [comment]
Please open a new Pull Request or an Issue for any new language so I can keep track of all of them. Thanks!

**Comment by kofzhanganguo** [comment]
Submit application Simplified Chinese translation, supplement all Chinese translations
[caesium_zh_CN.zip](https://github.com/Lymphatus/caesium-image-compressor/files/11364808/caesium_zh_CN.zip)

**Comment by Charltsing** [comment]
Simplified Chinese translation , caesium_zh_CN.ts

[caesium_zh_CN.zip](https://github.com/Lymphatus/caesium-image-compressor/files/15239098/caesium_zh_CN.zip)

and i am not found it in ts file
捕获

**Pull request merged**
